layout_spectrum: 0.5827067
typography_spectrum: 1
color:
  saturation: 0.9709688
  lightness: 0.5295771
  brandStrength: 0.6048838
  rhythmicContrast: 0.05725302
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
name: Bravo-Chavez
